openapi: 3.0.2
servers:
  - url: storetest/v3
info:
  version: 1.0.
  title: OpenAPI 3.0
  termsOfService: 'http://swagger.io/terms/'
tags:
  - name: user
    description: Everything about your Users
  - name: order
    description: Everything about your Orders
  - name: product
    description: Everything about your Products
  - name: employee
    description: Everything about your Products
paths:
  '/orders/findByStatus?status=done':
    get:
      tags:
        - order
      summary: Get order information
      operationId: getOrder
      parameters:
        - name: orderId
          in: query
          description: order identifier
          required: true
          schema:
            type: integer
            format: int64    
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              example:
                orderId: 1255125
                productName: updated_order
                productAmount: 515415
                status: done
        '401':
          description: Invalid ID supplied
      security:
        - oauth2:
            - read
  /user: 
    post:
      tags:
        - user
      summary: Create a new user
      operationId: CreateUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Success
          content:
            application/json:
              example:
                userId: 111
                name: new_user
                surname: new_userSurname
                number: new_number
                email: new_user@example.com
                numberDiscountCard: new_card
        '400':
          description: Invalid  value      
          content:
            application/json:
              example:
                code: 400
                message: Invalid  value   
      security:
        - oauth2:
            - read
            - write
  /employees/{idEmployees}:
    patch:
      tags:
        - employee
      summary: Partially update employee information
      operationId: updated
      parameters:
        - name: EmployeesId
          in: path
          description: employee information
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '200':
          description: Successful partial update
          content:
            application/json:
              example:
                EmployeesId: 26514
                number: 48415
        '400':
          description: Invalid  value      
          content:
            application/json:
              example:
                code: 400
                message: Invalid  value   
      security:
        - api_key: []
  /login:
    get:
      tags:
       - user
      description: Displaying the login page
      summary: Displaying the login page
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: object
                    description: Рage for entering login and login password
        '404':
          description: page not found
        '503':
          description: server error
    post:
      tags:
        - user
      summary: Login in system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Логин пользователя
                  example: Ksenia Solodovnik
                e-mail:
                  type: string
                  format: password
                  example: test@uandex.com
                password:
                  type: string
                  format: password
                  description: Пароль пользователя
                role:
                  type: string
                  enum:
                   - user
                   - employee
                  description: user role
                  example: employee
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Bearer Token для дальнейшей аутентификации
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        '401':
          description: Аuthentication error
        '500':
          description: Server rrror
  /orders/{orderId}:
    put:
      tags:
        - order
      summary: Update order information
      operationId: updated_order
      parameters:
        - name: orderId
          in: path
          description: Order identifier
          required: true
          schema:
            type: integer
      requestBody:
        description: Update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderUpdate'
      responses:
        '200':
          description: Successful update
          content:
            application/json:
              example:
                orderId: 1255125
                productName: updated_order
                productAmount: 515415
      security:
        - api_key: []    
  /products/{productId}:
    delete:
      tags:
        - product
      summary: Delete product
      operationId: deleteProduct
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Success
        '404':
          description: Product not found
          content:
            application/json:
              example:
                code: 400
                message: Invalid  value  
    put:
      tags:
        - employee
        - product
      summary: update product
      operationId: updateProduct
      security:
        - bearerAuth: []    
      parameters:
        - name: productId
          in: path
          description: ID товара, параметры которого нужно изменить
          required: true
          schema:
            type: integer
            example: 15454
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  productAmount:
                    type: integer
                    format: int64
                    example: 5
                  productName:
                    type: string
                    format: string
                    example: table
                  price:
                    type: integer
                    format: int64
                    example: 12.2515
        '404':
          description: product not found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdate'  
components:
  schemas:
    Order:
      x-swagger-router-model: io.swagger.model.Order
      properties:
        orderId:
          type: integer
          format: int64
          example: 198772
        productName:
          type: string
          format: product name
          example: table
        productAmount:
          type: integer
          format: int64
          example: 5
        status:
          type: string
          format: istatus order
          example: done
    OrderUpdate:
      x-swagger-router-model: io.swagger.model.Order
      properties:
        orderId:
          type: integer
          format: int64
          example: 198772
        token:
          type: string
          format: product name
          example: "eyJ0eXAwcvvcb1QiLCJhbGciOsdfsUzI1NiJ9"
        productAmount:
          type: integer
          format: int64
          example: 5
        productName:
          type: string
          format: string
          example: table
    User:
      x-swagger-router-model: io.swagger.model.User
      properties:
        name:
          type: string
          example: Petr
        surname:
          type: string
          example: Petrov
        email:
          type: string
          example: test@email.com
        number:
          type: string
          example: 12345
        numberDiscountCard:
          type: integer
          format: int64
          example: 97427
    Employee:
      x-swagger-router-model: io.swagger.model.Employee
      properties:      
        number:  
          type: string
          example: 47313
    Product:
      x-swagger-router-model: io.swagger.model.Product
      properties:
        productId:
          type: integer
          format: int64
          example: 10
    ProductUpdate:
      x-swagger-router-model: io.swagger.model.Order
      properties:
        productId:
          type: integer
          format: int64
          example: 198772
        token:
          type: string
          format: product name
          example: "eyJ0eXAwcvvcb1QiLCJhbGciOsdfsUzI1NiJ9"
    Deliveries:
      x-swagger-router-model: io.swagger.model.Deliveries
      properties:
        nameOrganization:
          type: string
          format: string
          example: Express
        inn:
          type: integer
          format: int64
          example: 45541215       
  requestBodies:
    user:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
    Deliveries:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Deliveries'        
    order:
       content:
        application/json:
          schema:
            $ref: '#/components/schemas/Order'
    Employee:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'    
  securitySchemes:
    auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://.swagger.io/oauth/authorize'
          scopes:
            'write': modify in your account
            'read': read your data
    api_key:
      type: apiKey
      name: api_key
      in: header          
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT  
     
  
          
